name: Process Emails

on:
  schedule:
    - cron: "0 * * * *"  # Agenda para rodar a cada 1 hora
  workflow_dispatch:  # Permite execução manual pelo GitHub

jobs:
  process_emails:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib

    - name: Run email processor
      env:
        GMAIL_TOKEN: ${{ secrets.GMAIL_TOKEN }}
      run: python process_emails.py
