name: Process Emails

on:
  schedule:
    - cron: '0 * * * *'  # Executar a cada 1 hora
  workflow_dispatch:

jobs:
  process:
    runs-on: ubuntu-22.04  # Especificar a versão do Ubuntu para evitar o futuro uso do ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the email processing script
        run: |
          python process_emails.py
        env:
          GMAIL_TOKEN: ${{ secrets.GMAIL_TOKEN }}

      - name: Verify generated files
        run: |
          ls -l  # Verifique se os arquivos foram criados
